version: "2"
services:
  php:
    image: mrubiosan/petstore:latest
    ports:
      - "8099:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
  db:
    ports:
      - "3316:3306"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: dev
